export const candles = [
  {
    id: 1,
    slug: 'sauvage',
    name: 'SAUVAGE',
    subtitle: 'Dior Sauvage',
    price: 55,
    size: '14oz',
    tag: 'Bestseller',
    notes: ['Calabrian Bergamot', 'Pink Pepper', 'Lavender', 'Ambroxan', 'Cedar', 'Vanilla'],
    coldThrow: 'Crisp bergamot, hint of pepper',
    warmThrow: 'Full woody amber, lavender haze, warm vanilla base',
    bestIn: ['Bedroom', 'Home office'],
    pairsWith: ['Morning coffee', 'Open windows', 'Linen sheets'],
    description: 'Raw, magnetic, untamed. Calabrian bergamot settles into a warm, woody embrace. For the one who walks into a room and changes it.',
    story: 'Inspired by the wide-open Sauvage desert at twilight \u2014 the air charged with wild herbs and heat rising off the rock. We captured that energy in a hand-poured soy blend that opens bright, then deepens into something you can\'t stop breathing in.',
    mood: 'Bold, fresh, magnetic',
    season: 'Spring / Summer',
    intensity: 4,
    bg: '#0F1724',
    labelBg: '#1a2744',
    glowColor: '147, 197, 253',
    moodImg: '/images/sauvage-mood.jpg',
    altImg: '/images/blue-mood.jpg',
  },
  {
    id: 2,
    slug: 'rouge',
    name: 'ROUGE',
    subtitle: 'Baccarat Rouge 540',
    price: 55,
    size: '14oz',
    tag: 'Most Gifted',
    notes: ['Saffron', 'Jasmine', 'Ambergris', 'Cedar', 'Fir Resin', 'Musk'],
    coldThrow: 'Warm saffron, soft jasmine',
    warmThrow: 'Rich amber cloud, resinous depth, clean musk that lingers',
    bestIn: ['Living room', 'Dining room'],
    pairsWith: ['Date night', 'Wine', 'Velvet everything'],
    description: 'Liquid crystal. Saffron and jasmine dissolve into luminous amber that lingers for hours \u2014 ethereal, addictive, unmistakable.',
    story: 'There\'s a reason people stop you to ask what you\'re burning. Rouge was built around the same molecular magic that made the original impossible to ignore \u2014 saffron cracking open, jasmine dissolving into a cloud of amber that stays in the room long after the flame goes out.',
    mood: 'Ethereal, warm, addictive',
    season: 'Fall / Winter',
    intensity: 5,
    bg: '#2A1019',
    labelBg: '#3d1826',
    glowColor: '253, 164, 175',
    moodImg: '/images/red-rose.jpg',
    altImg: '/images/candle-warm.jpg',
  },
  {
    id: 3,
    slug: 'guilty',
    name: 'GUILTY',
    subtitle: 'Gucci Guilty',
    price: 55,
    size: '14oz',
    tag: 'New',
    notes: ['Italian Mandarin', 'Pink Pepper', 'Lilac', 'Orange Blossom', 'Patchouli', 'Cedarwood'],
    coldThrow: 'Bright mandarin, sweet lilac',
    warmThrow: 'Smooth patchouli blanket, amber warmth, earthy cedar finish',
    bestIn: ['Bedroom', 'Bathroom', 'Any small space'],
    pairsWith: ['Late nights', 'Vinyl records', 'Rain on the window'],
    description: 'Unapologetic warmth. Italian mandarin gives way to a bold, impossibly smooth patchouli. For nights that don\'t end early.',
    story: 'Guilty is the one you light when the evening has no agenda. Italian mandarin cuts through with a citrus snap, then gives way to something deeper \u2014 lilac and orange blossom tangled with a patchouli so smooth it feels like velvet. This is the late-night candle.',
    mood: 'Sensual, daring, smooth',
    season: 'Year-round',
    intensity: 3,
    bg: '#1A1714',
    labelBg: '#2d2820',
    glowColor: '217, 194, 160',
    moodImg: '/images/guilty-mood.jpg',
    altImg: '/images/earth-mood.jpg',
  },
]

export const productSpecs = [
  { label: 'Burn Time', value: '60+ hours' },
  { label: 'Wax', value: '100% natural soy' },
  { label: 'Wick', value: 'Cotton, lead-free' },
  { label: 'Made In', value: 'Small batch, hand-poured' },
]
